load("@io_bazel_rules_docker//container:container.bzl", "container_image")
load("@debian10_bundle//:packages.bzl", "package")

container_image(
    name = "testimage",
    base = "@debian10//image",
    debs = [
        package("base-files"),
        package("ca-certificates"),
        package("dash"),
        package("libapparmor1"),
        package("libargon2-1"),
        package("libbz2-1.0"),
        package("libc-bin"),
        package("libc6"),
        package("libdb5.3"),
        package("libexpat1"),
        package("libfcgi-bin"),
        package("libfcgi0ldbl"),
        package("libffi6"),
        package("libgcc1"),
        package("libgcrypt20"),
        package("libgomp1"),
        package("libgpg-error0"),
        package("libicu63"),
        package("liblz4-1"),
        package("liblzma5"),
        package("libmagic1"),
        package("libncursesw5"),
        package("libpcre2-8-0"),
        package("libpcre3"),
        package("libpython2.7-minimal"),
        package("libpython2.7-stdlib"),
        package("libreadline7"),
        package("libsodium23"),
        package("libsqlite3-0"),
        package("libssl1.1"),
        package("libstdc++6"),
        package("libsystemd0"),
        package("libtinfo5"),
        package("libxml2"),
        package("mime-support"),
        package("netbase"),
        package("nginx-common"),
        package("nginx-light"),
        package("openssl"),
        package("php7.3-cli"),
        package("php7.3-common"),
        package("php7.3-fpm"),
        package("php7.3-json"),
        package("php7.3-mysql"),
        package("php7.3-opcache"),
        package("python-meld3"),
        package("python-pkg-resources"),
        package("python2.7-minimal"),
        package("readline-common"),
        package("supervisor"),
        package("tzdata"),
        package("zlib1g"),
    ],
    entrypoint = "/bin/sh",
)
